### ISSUE TITLE
Release version with current fixes

### ISSUE THREAD

**Issue by nawroth** [khmarbaise/exec-maven-plugin#1]
I specifically need the outputFile fix you committed.
Any chance to see a new version released to mvn central really soon?

**Comment by khmarbaise** [comment]
I will take a deeper look tomorrow, cause i'm working on several changes for the plugin....

**Comment by nawroth** [comment]
@khmarbaise It would be interesting to know if there's any new issues which were not present in the latest release.In other words, if no new issues have been introduced, it might be a good time to cut a release before even more changes go in.

**Comment by khmarbaise** [comment]
I deployed a SNAPSHOT of my current master...It would be nice if you check things here...

https://nexus.codehaus.org/content/repositories/snapshots/org/codehaus/mojo/exec-maven-plugin/1.3-SNAPSHOT/

**Comment by nawroth** [comment]
Thanks, I'll give it a try tomorrow.

**Comment by nawroth** [comment]
It works like a charm for my case!

**Comment by nawroth** [comment]
I found a different, better, solution for my case. But it's still great that this plugin will see some improvements in the next release!
